import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsBoolean, IsNotEmpty, IsOptional, IsString, Length } from 'class-validator';

export class NonceRequestDto {
  @ApiProperty({
    description: 'Solana wallet address used for authentication',
    example: 'CWZDCmkzzBSwQVMLaJ3ALpSAKJ9oGQoo9Jn8oN2TrNz',
  })
  @IsString()
  @IsNotEmpty()
  walletAddress: string;
}

export class VerifySignatureDto {
  @ApiProperty({
    description: 'Solana wallet address used for authentication',
    example: 'CWZDCmkzzBSwQVMLaJ3ALpSAKJ9oGQoo9Jn8oN2TrNz',
  })
  @IsString()
  @IsNotEmpty()
  walletAddress: string;

  @ApiProperty({
    description: 'Nonce that was signed by the wallet',
    example: 'ab12cd34ef56ab78cd90ef12ab34cd56',
  })
  @IsString()
  @IsNotEmpty()
  nonce: string;

  @ApiProperty({
    description: 'Signature generated by signing the nonce with the wallet private key (base58)',
    example: '2h2mqen3Li2iHLuTZHpZK5v6kqYgQHF2c3sJGyLeasAAVh2iPpStsZs8fPNGJX6vu1qS1H9oV67Sytja4K5iLTnq',
  })
  @IsString()
  @IsNotEmpty()
  signature: string;
}

export class RefreshTokenDto {
  @ApiProperty({
    description: 'Refresh token issued during login',
    example: '246bd6c6-54aa-4a1e-bfe0-3f57f31f261f',
  })
  @IsString()
  @IsNotEmpty()
  refreshToken: string;
}

export class LogoutRequestDto {
  @ApiPropertyOptional({
    description: 'When true, revoke every active session for current user',
    example: false,
  })
  @IsOptional()
  @IsBoolean()
  logoutAll?: boolean;
}

export class AuthTokensDto {
  @ApiProperty({ description: 'JWT access token used for authenticated requests' })
  @IsString()
  accessToken: string;

  @ApiProperty({ description: 'Access token lifetime in seconds', example: 900 })
  expiresIn: number;

  @ApiProperty({ description: 'Refresh token for renewing access tokens' })
  @IsString()
  refreshToken: string;

  @ApiProperty({
    description: 'Timestamp when refresh token expires',
    example: '2025-01-01T00:00:00.000Z',
  })
  @IsString()
  refreshTokenExpiresAt: string;
}

export class AuthUserDto {
  @ApiProperty({ description: 'Unique user identifier', example: 'b46d9d39-8c16-4d86-9b54-4a7f5ddf5e04' })
  id: string;

  @ApiProperty({ description: 'Primary wallet address used during login' })
  walletAddress: string;

  @ApiPropertyOptional({ description: 'Display name shown on leaderboard or profile' })
  displayName?: string;

  @ApiPropertyOptional({ description: 'Avatar image url' })
  avatarUrl?: string;
}

export class AuthResponseDto {
  @ApiProperty({ description: 'Authenticated user information', type: AuthUserDto })
  user: AuthUserDto;

  @ApiProperty({ description: 'Tokens issued for the authenticated session', type: AuthTokensDto })
  tokens: AuthTokensDto;
}