import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsEnum,
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUUID,
  Length,
} from 'class-validator';
import { VipRoomType, VipTicketStatus } from '@/database/entities';

export class VipRoomConfigDto {
  @ApiProperty({
    description: 'Room type identifier',
    enum: VipRoomType,
    example: VipRoomType.SNAKE_VIP,
  })
  @IsEnum(VipRoomType)
  roomType: VipRoomType;

  @ApiProperty({
    description: 'Entry fee in credits formatted with token decimals',
    example: '1.000000',
  })
  entryFee: string;

  @ApiProperty({
    description: 'Reward amount given to the killer',
    example: '0.900000',
  })
  rewardRatePlayer: string;

  @ApiProperty({
    description: 'Fee amount retained by the treasury',
    example: '0.100000',
  })
  rewardRateTreasury: string;

  @ApiProperty({
    description: 'Amount deducted when respawning (if enabled)',
    example: '0.000000',
  })
  respawnCost: string;

  @ApiProperty({
    description: 'Maximum number of clients allowed in the room',
    example: 20,
  })
  maxClients: number;

  @ApiProperty({
    description: 'Target tick rate for the room',
    example: 60,
  })
  tickRate: number;

  @ApiProperty({
    description: 'Flag indicating whether the configuration is active',
    example: true,
  })
  isActive: boolean;

  @ApiPropertyOptional({
    description: 'Optional configuration metadata',
    example: {
      description: 'VIP snake room configuration',
    },
  })
  metadata?: Record<string, unknown>;
}

export class VipTicketInfoDto {
  @ApiProperty({
    description: 'Ticket identifier',
    example: 'a4abf4f1-7054-4c6a-94b9-5a41f9991d51',
  })
  id: string;

  @ApiProperty({
    description: 'Ticket reference code',
    example: '8d3e8725-55d2-4b64-8ec2-6bdac74a3e4c',
  })
  ticketCode: string;

  @ApiProperty({
    description: 'Entry fee stored in the ticket',
    example: '1.000000',
  })
  entryFee: string;

  @ApiProperty({
    description: 'Ticket status',
    enum: VipTicketStatus,
    example: VipTicketStatus.ISSUED,
  })
  status: VipTicketStatus;

  @ApiProperty({
    description: 'Room type associated with the ticket',
    enum: VipRoomType,
    example: VipRoomType.SNAKE_VIP,
  })
  roomType: VipRoomType;

  @ApiPropertyOptional({
    description: 'Room instance identifier if the ticket has been consumed',
    example: 'vip-room-1',
  })
  roomInstanceId?: string;

  @ApiPropertyOptional({
    description: 'Ticket expiration timestamp',
    example: '2025-01-01T00:00:00.000Z',
  })
  expiresAt?: Date;

  @ApiPropertyOptional({
    description: 'Ticket consumption timestamp',
    example: '2024-12-31T23:59:59.000Z',
  })
  consumedAt?: Date;
}

export class VipAccessCheckRequestDto {
  @ApiPropertyOptional({
    description: 'Requested room type',
    enum: VipRoomType,
    example: VipRoomType.SNAKE_VIP,
  })
  @IsOptional()
  @IsEnum(VipRoomType)
  roomType?: VipRoomType;
}

export class VipAccessCheckResponseDto {
  @ApiProperty({
    description: 'Flag indicating whether the user can join the room',
    example: true,
  })
  canJoin: boolean;

  @ApiProperty({
    description: 'User credit balance after the check',
    example: '5.000000',
  })
  credit: string;

  @ApiPropertyOptional({
    description: 'VIP ticket information when access is granted',
    type: VipTicketInfoDto,
  })
  ticket?: VipTicketInfoDto;

  @ApiPropertyOptional({
    description: 'Active configuration applied to the request',
    type: VipRoomConfigDto,
  })
  config?: VipRoomConfigDto;

  @ApiPropertyOptional({
    description: 'Reason when access is denied',
    example: 'Insufficient credit to join VIP room',
  })
  reason?: string;
}

export class VipConsumeTicketRequestDto {
  @ApiProperty({
    description: 'VIP ticket identifier',
    example: 'a4abf4f1-7054-4c6a-94b9-5a41f9991d51',
  })
  @IsUUID()
  ticketId: string;

  @ApiProperty({
    description: 'Room instance identifier generated by Colyseus',
    example: 'snake-game-vip-001',
  })
  @IsString()
  @IsNotEmpty()
  @Length(1, 64)
  roomInstanceId: string;
}

export class VipConsumeTicketResponseDto {
  @ApiProperty({
    description: 'Updated user credit after consuming the ticket',
    example: '4.000000',
  })
  credit: string;

  @ApiProperty({
    description: 'Ticket information after consumption',
    type: VipTicketInfoDto,
  })
  ticket: VipTicketInfoDto;
}

export class VipValidateTicketRequestDto {
  @ApiProperty({
    description: 'Ticket identifier to validate',
    example: 'a4abf4f1-7054-4c6a-94b9-5a41f9991d51',
  })
  @IsUUID()
  ticketId: string;
}

export class VipValidateTicketResponseDto {
  @ApiProperty({
    description: 'Ticket information',
    type: VipTicketInfoDto,
  })
  ticket: VipTicketInfoDto;

  @ApiProperty({
    description: 'Active configuration for the ticket room type',
    type: VipRoomConfigDto,
  })
  config: VipRoomConfigDto;

  @ApiProperty({
    description: 'User credit balance at validation time',
    example: '5.000000',
  })
  credit: string;
}

export class VipKillRewardRequestDto {
  @ApiProperty({
    description: 'Killer ticket identifier',
    example: 'b15f9ef0-21d7-4f2b-9e39-1f94c82a93ed',
  })
  @IsUUID()
  killerTicketId: string;

  @ApiProperty({
    description: 'Victim ticket identifier',
    example: 'c27a211e-7f07-43f6-a6f4-2d94f5d93f30',
  })
  @IsUUID()
  victimTicketId: string;

  @ApiProperty({
    description: 'Unique kill reference generated by the game server',
    example: 'kill-6db9a3e6-0d78-4982-9b62-ae948fd1c85a',
  })
  @IsString()
  @IsNotEmpty()
  @Length(1, 64)
  killReference: string;

  @ApiProperty({
    description: 'Room instance identifier where the kill happened',
    example: 'snake-game-vip-001',
  })
  @IsString()
  @IsNotEmpty()
  @Length(1, 64)
  roomInstanceId: string;
}

export class VipKillRewardResponseDto {
  @ApiProperty({
    description: 'Killer credit after applying the reward',
    example: '6.800000',
  })
  killerCredit: string;

  @ApiProperty({
    description: 'Victim credit after deducting the penalty',
    example: '2.100000',
  })
  victimCredit: string;

  @ApiProperty({
    description: 'Reward amount granted to the killer',
    example: '0.900000',
  })
  rewardAmount: string;

  @ApiProperty({
    description: 'Fee amount retained by the treasury',
    example: '0.100000',
  })
  feeAmount: string;

  @ApiProperty({
    description: 'Flag indicating whether the request was already processed',
    example: false,
  })
  alreadyProcessed: boolean;
}

export class VipRespawnRequestDto {
  @ApiProperty({
    description: 'Ticket identifier used by the player',
    example: 'a4abf4f1-7054-4c6a-94b9-5a41f9991d51',
  })
  @IsUUID()
  ticketId: string;
}

export class VipRespawnResponseDto {
  @ApiProperty({
    description: 'User credit after processing the respawn logic',
    example: '3.500000',
  })
  credit: string;
}
